CREATE TABLE instantaneous (
    MeterSerialNumber VARCHAR(20) NOT NULL,
    readingdate TIMESTAMP,
    meterdate TIMESTAMP,
    ActivePlus NUMERIC(20,5),
    ActivePlusR NUMERIC(20,5),
    ActivePlusS NUMERIC(20,5),
    ActivePlusT NUMERIC(20,5),
    ActiveMin NUMERIC(20,5),
    ActiveMinR NUMERIC(20,5),
    ActiveMinS NUMERIC(20,5),
    ActiveMinT NUMERIC(20,5),
    REACTIVEPLUS NUMERIC(20,5),
    REACTIVEPLUSR NUMERIC(20,5),
    REACTIVEPLUSS NUMERIC(20,5),
    REACTIVEPLUST NUMERIC(20,5),
    ReactiveMin NUMERIC(20,5),
    ReactiveMinR NUMERIC(20,5),
    ReactiveMinS NUMERIC(20,5),
    ReactiveMinT NUMERIC(20,5),
    ReactiveBilling NUMERIC(20,5),
    CURRENT1 NUMERIC(15,5),
    CURRENT2 NUMERIC(15,5),
    CURRENT3 NUMERIC(15,5),
    CURRENTNet NUMERIC(15,5),
    CURRENTTHD NUMERIC(15,5),
    CURRENTTDD NUMERIC(15,5),
    VOLTAGE1 NUMERIC(15,5),
    VOLTAGE2 NUMERIC(15,5),
    VOLTAGE3 NUMERIC(15,5),
    CosPhi1 NUMERIC(15,5),
    CosPhi2 NUMERIC(15,5),
    CosPhi3 NUMERIC(15,5),
    CosPhi NUMERIC(15,5),
    ActPlusPwr NUMERIC(15,5),
    ActPlusPwrR NUMERIC(15,5),
    ActPlusPwrS NUMERIC(15,5),
    ActPlusPwrT NUMERIC(15,5),
    ActMinPwr NUMERIC(15,5),
    ActMinPwrR NUMERIC(15,5),
    ActMinPwrS NUMERIC(15,5),
    ActMinPwrT NUMERIC(15,5),
    RectPlusPwr NUMERIC(15,5),
    RectPlusPwrR NUMERIC(15,5),
    RectPlusPwrS NUMERIC(15,5),
    RectPlusPwrT NUMERIC(15,5),
    RectMinPwr NUMERIC(15,5),
    RectMinPwrR NUMERIC(15,5),
    RectMinPwrS NUMERIC(15,5),
    RectMinPwrT NUMERIC(15,5),
    AppPlusPwr NUMERIC(15,5),
    AppPlusPwrR NUMERIC(15,5),
    AppPlusPwrS NUMERIC(15,5),
    AppPlusPwrT NUMERIC(15,5),
    AppMinPwr NUMERIC(15,5),
    AppMinPwrR NUMERIC(15,5),
    AppMinPwrS NUMERIC(15,5),
    AppMinPwrT NUMERIC(15,5),
    Frequency NUMERIC(15,5),
    AngleL1 NUMERIC(15,5),
    AngleL2 NUMERIC(15,5),
    AngleL3 NUMERIC(15,5),
    AngleVL1 NUMERIC(15,5),
    AngleVL2 NUMERIC(15,5),
    AngleVL3 NUMERIC(15,5),
    CT_Ratio VARCHAR(15),
    VT_Ration VARCHAR(15),
    AngleVI_L1 NUMERIC(15,5),
    AngleVI_L2 NUMERIC(15,5),
    AngleVI_L3 NUMERIC(15,5),
    Battery NUMERIC(15,5),
    TypeDial SMALLINT DEFAULT 0,
    RemainingCredit NUMERIC(15,5),
    readingdate_day DATE GENERATED ALWAYS AS (readingdate::date) STORED,
    CONSTRAINT instantaneous_index01 UNIQUE (MeterSerialNumber, readingdate)
);

-- Additional indexes (optional, based on MySQL definition)
CREATE INDEX instantaneous_index02 ON instantaneous (MeterSerialNumber);
CREATE INDEX instan_date ON instantaneous (readingdate_day);
CREATE INDEX instan_date2 ON instantaneous (readingdate_day, MeterSerialNumber);

CREATE TABLE billingregister (
  MeterSerialNumber VARCHAR(20) NOT NULL,
  ReadingDate TIMESTAMP NOT NULL,
  BillingDate TIMESTAMP NOT NULL,
  ActivePlusT1 NUMERIC(20,5),
  ActivePlusT2 NUMERIC(20,5),
  ActivePlusT3 NUMERIC(20,5),
  ActivePlusT4 NUMERIC(20,5),
  ActivePlusT5 NUMERIC(20,5),
  ActivePlus NUMERIC(20,5),
  ActiveMinusT1 NUMERIC(20,5),
  ActiveMinusT2 NUMERIC(20,5),
  ActiveMinusT3 NUMERIC(20,5),
  ActiveMinusT4 NUMERIC(20,5),
  ActiveMinusT5 NUMERIC(20,5),
  ActiveMinus NUMERIC(20,5),
  ReactivePlus NUMERIC(20,5),
  ReactivePlusT1 NUMERIC(20,5),
  ReactivePlusT2 NUMERIC(20,5),
  ReactivePlusT3 NUMERIC(20,5),
  ReactivePlusT4 NUMERIC(20,5),
  ReactivePlusT5 NUMERIC(20,5),
  ReactiveMinus NUMERIC(20,5),
  ReactiveMinusT1 NUMERIC(20,5),
  ReactiveMinusT2 NUMERIC(20,5),
  ReactiveMinusT3 NUMERIC(20,5),
  ReactiveMinusT4 NUMERIC(20,5),
  ReactiveMinusT5 NUMERIC(20,5),
  ApparentPlus NUMERIC(20,5),
  ApparentPlusT1 NUMERIC(20,5),
  ApparentPlusT2 NUMERIC(20,5),
  ApparentPlusT3 NUMERIC(20,5),
  ApparentPlusT4 NUMERIC(20,5),
  ApparentPlusT5 NUMERIC(20,5),
  ApparentMinus NUMERIC(20,5),
  ApparentMinusT1 NUMERIC(20,5),
  ApparentMinusT2 NUMERIC(20,5),
  ApparentMinusT3 NUMERIC(20,5),
  ApparentMinusT4 NUMERIC(20,5),
  ApparentMinusT5 NUMERIC(20,5),
  ReactivePlusBilling NUMERIC(20,5),
  MD NUMERIC(20,5),
  MDT1 NUMERIC(20,5),
  MDT2 NUMERIC(20,5),
  MDT3 NUMERIC(20,5),
  MDT4 NUMERIC(20,5),
  MDT5 NUMERIC(20,5),
  MD_Time TIMESTAMP,
  MDT1_Time TIMESTAMP,
  MDT2_Time TIMESTAMP,
  MDT3_Time TIMESTAMP,
  MDT4_Time TIMESTAMP,
  MDT5_Time TIMESTAMP,
  NumberPwrOff NUMERIC(20,5),
  NumberTamper NUMERIC(20,5),
  Battery NUMERIC(20,5),
  BillingDateDay DATE GENERATED ALWAYS AS (BillingDate::date) STORED
);

-- Indexes
CREATE INDEX billingregister_index01 ON billingregister (MeterSerialNumber);
CREATE INDEX billingregister_index02 ON billingregister (BillingDate);
CREATE INDEX billingregister_index03 ON billingregister (MeterSerialNumber, BillingDate);
CREATE INDEX billingregister_index04 ON billingregister (ReadingDate);
CREATE INDEX billingregister_index05 ON billingregister (MeterSerialNumber, ReadingDate);
CREATE INDEX billing_date ON billingregister (BillingDateDay);


CREATE TABLE loadprofile (
  MeterSerialNumber VARCHAR(20) NOT NULL,
  ReadingTime TIMESTAMP NOT NULL,
  LPTime TIMESTAMP NOT NULL,
  ActPlus NUMERIC(15,5),
  ActMin NUMERIC(15,5),
  ReactPlus NUMERIC(15,5),
  ReactMin NUMERIC(15,5),
  V1 NUMERIC(15,5),
  V2 NUMERIC(15,5),
  V3 NUMERIC(15,5),
  I1 NUMERIC(15,5),
  I2 NUMERIC(15,5),
  I3 NUMERIC(15,5),
  Frequency NUMERIC(15,5),
  PowerFactor NUMERIC(15,5),
  AR VARCHAR(75),
  EnergyMonthly NUMERIC(15,5),
  Status INTEGER,
  ActPwrPlus NUMERIC(15,5),
  ActPwrMin NUMERIC(15,5),
  PRIMARY KEY (MeterSerialNumber, LPTime)
);

-- Indexes
CREATE UNIQUE INDEX loadprofile_index01 ON loadprofile (MeterSerialNumber, LPTime);
CREATE INDEX idx_loadprofile ON loadprofile (MeterSerialNumber);
CREATE INDEX loadprofile_index02 ON loadprofile (LPTime);
CREATE INDEX loadprofile_index03 ON loadprofile (ReadingTime);
CREATE INDEX loadprofile_index04 ON loadprofile (MeterSerialNumber, ReadingTime);
